chat/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

urlpatterns = [
    # path('api/', views.ChatListView.as_view()),
    path('upload_files', views.upload_file, name='upload-file'),
    path('close', views.chat_close, name='chat-close'),
    path('pdf_view/<file_name>', views.pdf_view, name='pdf-view'),
    path('make-invest', views.make_chat_invest, name='chat-invest'),
    path('make-advise', views.make_chat_advisor, name='chat-advise'),
    path('make-sell', views.make_chat_seller, name='chat-sell'),
    path('fetch-sell/<business_id>', views.fetch_sell_id, name='fetch-sell-id'),
    path('api/<username>', views.get_all_chats),
    path('create/', views.ChatCreateView.as_view()),
    path('<pk>', views.ChatDetailView.as_view()),
    path('<pk>/update/', views.ChatUpdateView.as_view()),
    path('<pk>/delete/', views.ChatDeleteView.as_view()),
    url(r'^$', views.index, name='index'),
    path('<room_name>/', views.room, name='room'),
    path('check_chat', views.staff_check_connection, name='check_chat'),
    path('close_service', views.staff_close_connection, name='close_service'),
    path('send_whatsapp_message', views.send_whatsapp_message, name='send_whatsapp_message'),
    path('handle_incoming_messages', views.handle_incoming_messages, name='handle_incoming_messages'),


]

profiles/urls.py
from django.urls import path,  include
from profiles import views
import seller1.views as sell_views
import seller1.sms as sms
# from rest_framework.urlpatterns import format_suffix_patterns

handler404 = views.handler404
handler500 = views.handler500

urlpatterns = [
    path('', views.home_view, name='index'),
    path('subscribe', views.subscription, name='subscription'),
    path('pricing', views.pricing, name='pricing'),
    path('terms', views.terms, name='terms'),
    path('process_subscription', views.process_subscription, name='process_subscription'),
    path('payment-done/', views.payment_done, name='payment_done'),
    path('payment-cancelled/', views.payment_canceled, name='payment_canceled'),
    path('signup', views.register_view, name='signup'),
    path('user_profile', sell_views.user_profile, name='user-profile'),
    path('user_dashboard', sell_views.indiv_dash, name='user-dash'),
    path('user_dashboard2', sell_views.indiv_dash2, name='user-dash2'),
    path('check_email', views.check_email, name='check-email'),
    path('check_username', views.check_username, name='check-username'),
    path('clear_notif', views.clear_notif, name='clear-notif'),
    path('user/check_email', sms.check_email_otp, name='user-email-otp'),
    path('edit_profile', views.edit_profile , name='edit-profile'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('get_user', views.getUser.as_view(), name='get-user'),
    path('con_password', views.password_confirm, name='con-password'),
    path('chng_password', views.password_change, name='chng-password'),
    path('retive_notif', views.notif_data, name='retive_notif'),
    path('delete_profile', views.delete_profile, name='delete_profile'),
    path('clear_notif', views.clear_notif, name='clear_notif'),
    path('feedback_submit', views.feedback_submit, name='feedback_submit'),
    path('auth_error', views.auth_error, name='auth_error'),
    path('unlock_premium', sell_views.unlock_premium, name='unlock_premium'),

]

projectx/urls.py
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url


urlpatterns = [
    re_path(r'^', include(('profiles.urls', 'profiles'), namespace='profiles')),
    re_path(r'^seller/', include(('seller1.urls', 'seller1'), namespace='seller1')),
    re_path(r'^metadata/', include(('metadata.urls', 'metadata'), namespace='metadata')),
    re_path(r'^album/', include(('album.urls', 'album'), namespace='album')),
    re_path(r'^chat/', include(('chat.urls', 'chat'), namespace='chat')),
    re_path(r'^investor/', include(('investor.urls', 'investor'), namespace='investor')),
    re_path(r'^advisor/', include(('advisor.urls', 'advisor'), namespace='advisor')),
    re_path(r'^staff/authorize/login/', include(('staff.urls', 'staff'), namespace='staff   ')),
    re_path(r'^oauth/', include('social_django.urls', namespace='social')),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/forms.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.http import Http404
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from uuid import UUID
from django.shortcuts import get_object_or_404
from django.shortcuts import render, redirect
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django import forms
from django.contrib.auth import authenticate, login
from .models import Profile, Feedback


class UserRegisterForm(forms.ModelForm):

    email = forms.EmailField(label='Email address')
    password = forms.CharField(widget=forms.PasswordInput, label='Password')
    password2 = forms.CharField(widget=forms.PasswordInput, label='Confirm Password')

    class Meta:
        model = User
        fields = [
            'username',
            'email',
            'password',
            'password2',
        ]

    def clean(self, *args, **kwargs):
        email = self.cleaned_data.get('email')
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        password2 = self.cleaned_data.get('password2')
        if password != password2:
            raise forms.ValidationError("Passwords must match")
        email_qs = User.objects.filter(email=email)
        if email_qs.exists():
            raise forms.ValidationError(
                "This email has already been registered")
        return super(UserRegisterForm, self).clean(*args, **kwargs)


class UserLoginForm(forms.Form):
    email = forms.EmailField(label='Email address')
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self, *args, **kwargs):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')
        username = User.objects.get(email=email.lower()).username

        if email and password:
            user = authenticate(username=username, password=password)
            if not user:
                raise forms.ValidationError('This user does not exist')
            if not user.check_password(password):
                raise forms.ValidationError('Incorrect password')
            # if not user.is_active:
            #     raise forms.ValidationError('This user is not active')
        return super(UserLoginForm, self).clean(*args, **kwargs)

class ProfileForm(forms.ModelForm):
    contact_number = forms.IntegerField()
    country_code_primary = forms.CharField()
    class Meta:
        model = Profile
        exclude = ['user', 'created_at']

subscription_options = [
    ('1-month', '1-Month subscription ($10 USD/Mon)'),
    ('trial', 'Free Trial Period for 1 Month'),
    ('6-month', '6-Month subscription Save $10 ($50 USD/Mon)'),
    ('1-year', '1-Year subscription Save $30 ($90 USD/Mon)'),
]

class FeedbackForm(forms.ModelForm):
    # contact_number = forms.IntegerField()
    class Meta:
        model = Feedback
        exclude = ['created_at']

class SubscriptionForm(forms.Form):
    plans = forms.ChoiceField(choices=subscription_options)

profiles/views.py
from datetime import datetime

from django.contrib.auth import (
    authenticate,
    get_user_model,
    login,
    logout
)
from django.urls import reverse
import json
from django.http import Http404
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from uuid import UUID
from django.shortcuts import get_object_or_404
from django.shortcuts import render, redirect
from django.views import generic
from django.views.generic import View
from django import forms
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from social_django.models import UserSocialAuth

from advisor.serializers import AdvisorSerializer
from advisor.views import adv_model_list, adv_serializer_list
from album.models import KAlbumForFile, File
from investor.serializers import InvestorSerializer
from investor.views import inv_model_list, inv_serializer_list
from seller1.models import RevenueModel
from seller1.serializers import SellerSerializer, RevenueModelSerializer, serializer_list
from seller1.views import model_list
from staff.models import PhoneModel, EmailModel
from user_seller.models import Sell, Advise, Invest
from .models import Profile, Notification
from profiles.forms import UserLoginForm, UserRegisterForm, ProfileForm, SubscriptionForm, FeedbackForm
from django.http import JsonResponse
from metadata.views import business_sector, companies,codedata,yeardata
from .serializers import UserSerializer, ProfileSerializer
from chat.models import Chat, Contact, Notify, StaffChat, StaffMessage
from chat.views import get_user_contact, get_chat
from paypal.standard.forms import PayPalPaymentsForm
from django.views.decorators.csrf import csrf_exempt
from projectx import settings
from twilio.rest import Client
from django.core import serializers


def login_view(request):
    try:
        form = UserLoginForm(request.POST or None)
    except:
        data = {}
        data['status'] = 'invalid'
        # data['img_name'] = name
        print(data)
        # return redirect('seller1:seller')
        return JsonResponse(data, safe=False)
    try:
        if form.is_valid():

            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password')
            try:
                username = User.objects.get(email=email.lower()).username
            except:
                data={}
                data['status'] = 'invalid'
                # data['img_name'] = name
                print(data)
                # return redirect('seller1:seller')
                return JsonResponse(data, safe=False)
            # user = User.objects.get(username=username)
            # if not user.profile.active:
            #     data = {}
            #     data['status'] = 'invalid'
            #     return JsonResponse(data, safe=False)
            try:
                user = authenticate(username=username, password=password)
            except:
                data={}
                data['status'] = 'invalid'
                # data['img_name'] = name
                print(data)
                # return redirect('seller1:seller')
                return JsonResponse(data, safe=False)
            login(request, user)
            data = {}

            name=user.profile.photo.name
            data['status'] ='success'
            data['img_name']=name
            print(data)
            # return redirect('seller1:seller')
            return JsonResponse(data, safe=False)
    except:
        data = {}
        data['status'] = 'invalid'
        # data['img_name'] = name
        print(data)
        # return redirect('seller1:seller')
        return JsonResponse(data, safe=False)

    context = {
        'form': form,
    }
    data={}
    data['status']='no post request made'
    # return render(request, "login.html", context)
    return JsonResponse(data, safe=False)



def register_view(request):
    # next = request.GET.get('next')
    try:
        form = UserRegisterForm(data=request.POST or None)
        profile_form = ProfileForm(data=request.POST, files=request.FILES or None)
    except:
        data = {}
        data['status'] = 'invalid'
        # data['img_name'] = name
        print(data)
        # return redirect('seller1:seller')
        return JsonResponse(data, safe=False)
    if form.is_valid() and profile_form.is_valid():
        user = form.save(commit=False)
        password = form.cleaned_data.get('password')
        user.set_password(password)
        user.save()
        user.profile.first_name=profile_form.cleaned_data['first_name']
        print('0')
        user.profile.last_name = profile_form.cleaned_data['last_name']
        print('1')

        try:
            user.profile.contact_number = profile_form.cleaned_data['country_code_primary']+profile_form.cleaned_data['contact_number']
            print('2')
            user.profile.photo = request.FILES['photo']
            print(request.FILES['photo'])
        except:
            try:
                file = File.objects.get(name='category/advisor-img2.png')
            except:
                file = File()
                file.file.name = 'category/advisor-img2.png'
                file.save()
            user.profile.photo = file.file
            pass
        # user.profile.about_me = profile_form.cleaned_data['about_me']
        print('2')
        try:
            user.profile.country = profile_form.cleaned_data['country']
            print('2')
            user.profile.region = profile_form.cleaned_data['region']
            print('2')
            user.profile.city = profile_form.cleaned_data['city']
            print('2')
            user.profile.lngt = profile_form.cleaned_data['lngt']
            print('2')
            user.profile.lat = profile_form.cleaned_data['lat']
            print('2')
            user.profile.address_line = profile_form.cleaned_data['address_line']
            print('2')
        except:
            pass


        # profile.user = user
        user.save()
        print('3')
        new_user = authenticate(username=user.username, password=password)
        login(request, new_user)
        # client = user
        # phone_model = None
        # if user.profile.contact_number != '':
        #     phone_model = PhoneModel()
        #     phone_model.phone_number = user.profile.contact_number
        #     phone_model.country_code_primary = profile_form.cleaned_data['country_code_primary']
        #     phone_model.user = client
        #     phone_model.save()
        # email_model = EmailModel()
        # email_model.email = user.email
        # email_model.user = user
        # email_model.save()
        #
        # chat = StaffChat()
        # chat.client = client
        # chat.expiry_time = datetime.utcnow()
        # chat.bverge_open = False
        # chat.pending = False
        # chat.phone_model = phone_model
        # chat.save()
        # message = StaffMessage()
        # message.client = client
        # message.chat = chat
        # # message.malbum = malbum
        # message.file_exist = False
        # message.from_bverge = True
        # message.content = request.POST['message']
        # message.save()
        # body = 'Hi ' + client.first_name + ' ' + client.last_name + \
        #        ', Welcome to Business Verge! \n' \
        #        'We are a business networking platform and help' \
        #        ' Businesses and Startups to connect to beneficial Businesses, Investors and Advisors. \n' \
        #        'Please, reply with your details to help BVerge to list your need.'
        #
        # account_sid = 'ACdd657d4ed521eff8bd750ca7de57142c'
        # auth_token = '17591dd653a6f4c24965d63ddb08ccd8'
        # client = Client(account_sid, auth_token)
        # phone_number = chat.phone_model.phone_number
        # to_ = 'whatsapp:' + phone_number
        # send_message = client.messages \
        #     .create(
        #     from_='whatsapp:+14155238886',
        #     body=body,
        #     to=to_
        # )
        # print(send_message.sid)

        data = {}
        name = user.profile.photo.name
        data['status'] = 'success'
        data['img_name'] = name
        print(data)
        # return redirect('seller1:seller')
        # return redirect('profiles:signup')
        return JsonResponse(data, safe=False)
    print(profile_form.errors)
    print(form.errors)
    context = {
        'form': form,
        'profile_form': profile_form
    }
    data = {}
    data['status'] = 'no post request made'
    # return render(request, "signup.html", context)
    return JsonResponse(data, safe=False)


def logout_view(request):
    logout(request)
    return redirect('profiles:index')




def home_view(request):
    log_form = UserLoginForm()
    reg_form = UserRegisterForm()
    profile_form = ProfileForm()
    code_data = codedata()
    sectors = business_sector()
    print(sectors)
    notifications=None
    notif_number = None
    try:
        user = request.user
        notifications = user.profile.notifs.all().order_by('-created_at')
        notif_number=0
        for notif in notifications:
            if notif.notif_seen==False:
                notif_number=notif_number+1
    except:
        print('user is not authenticated')
        pass


    # num_visits = request.session.get('num_visits', 0)
    # request.session['num_visits'] = num_visits + 1
    similar_sellers = []
    similar_sell = Sell.objects.all()
    for similar_seller in similar_sell:
        investor = similar_seller.seller
        # if seller == investor:
        #     continue
        serializer = SellerSerializer(investor)
        x = serializer.data
        album_id = investor.album_id
        album = KAlbumForFile.objects.get(album_id=album_id)
        file = album.files.all()[0]
        file_name = file.name
        y = {
            'file_name': file_name,

profiles/templates/auth_error.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load staticfiles %}
    {% load widget_tweaks %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>BVerge- AI Enabled platform for Business search</title>
    <link rel="stylesheet" href="/static/profiles/css/bootstrap.min.css">
    <link rel="icon" href="/static/profiles/images/icon1.png">
    <link rel="stylesheet" href="/static/profiles/css/w3.css">
    <!-- <link rel="stylesheet" href="{% static 'profiles/css/jquery-ui.min.css' %}"> -->
    <link rel="stylesheet" href="/static/profiles/css/style.css">
    <link rel="stylesheet" href="/static/profiles/css/notification.css">
    <!-- <link rel="stylesheet" href="{% static 'profiles/css/parsley.css' %}"> -->
    <!-- <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/w3.css">
    <link rel="stylesheet" href="css/style.css"> -->
    <link rel="stylesheet" href="/static/seller1/css/owl.carousel.min.css">
    <link rel="stylesheet" href="/static/seller1/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/css/select2.min.css" rel="stylesheet" />
    <meta property="og:locale" content="en_US" />
    <meta property="og:type" content="website" />
    <meta property="og:title" content="Bverge"/>

    <!-- <meta property="og:description" content="Index Page"/>
    <meta property='og:url' content='http://13.127.153.254/' />
    <meta property="og:site_name" content="Bverge"/>
    <meta property="og:updated_time" content="2018-01-09T00:01:51+05:30" />
    <meta property="og:image" itemprop="image"  content="http://13.127.153.254/static/seller1/images/Bitmap.png"/>
    <meta property="og:image:secure_url" itemprop="image"  content="http://13.127.153.254/static/seller1/images/Bitmap.png"/>
    <meta property="og:image:width" content="958">
    <meta property="og:image:height" content="698">
    <meta property="og:image:type" content="image/png"/> -->
</head>



<style>
    #feeback_modal .close{
    position: absolute;
    right: 16px;
    top: 18px;
    padding: 8px;
    }
    #modal_edit_profile .close{
    position: absolute;
    right: 16px;
    top: 18px;
    padding: 8px;
    }
    #modal_change_password .close{
    position: absolute;
    right: 16px;
    top: 18px;
    padding: 8px;
    }
    #signup .profile_section{
    display: flex;
    flex-direction: column;
    justify-content: space-between;
    }
    .f-40{
    font-size: 40px;
    }
    .modal-content{
    box-shadow:2px 3px 10px 0px rgba(0,0,0,1);
    }

    .pac-container {
        z-index:20000;
    }
    .lodal {
        display:    none;
        position:   fixed;
        z-index:    1000000000000000;
        top:        0;
        left:       0;
        height:     100%;
        width:      100%;
        background: rgba( 255, 255, 255, .8 )
                    url('https://i.stack.imgur.com/FhHRx.gif')
                    50% 50%
                    no-repeat;
    }
    #mlodal {

        position:   fixed;
        z-index:    10000000000000000;
        top:        0;
        left:       0;
        height:     100%;
        width:      100%;
        background: rgba( 255, 255, 255, .8 )
                    url('https://i.stack.imgur.com/FhHRx.gif')
                    50% 50%
                    no-repeat;
    }
    #nlodal_s {

position:   fixed;
z-index:    10000000000000000;
top:        0;
left:       0;
height:     100%;
width:      100%;
background: rgba( 255, 255, 255, .8 )
            url('https://i.stack.imgur.com/FhHRx.gif')
            50% 50%
            no-repeat;
}
#nlodal_b {

position:   fixed;
z-index:    10000000000000000;
top:        0;
left:       0;
height:     100%;
width:      100%;
background: rgba( 255, 255, 255, .8 )
            url('https://i.stack.imgur.com/FhHRx.gif')
            50% 50%
            no-repeat;
}

    /* When the body has the loading class, we turn
    the scrollbar off with overflow:hidden */
    body.loading .lodal {
        overflow: hidden;
    }

    /* Anytime the body has the loading class, our
    modal element will be visible */
    body.loading .lodal {
        display: block;
    }
    div#notif_loader_s.loading .lodal {
        overflow: hidden;
    }
    div#notif_loader_s.loading .lodal {
        display: block;
    }
    .h-51{
    height: 51px !important;
    }
    .border-r-0{
    border-top-right-radius: 0;
    border-bottom-right-radius: 0;
    }
    .border-r-all{
    border-radius: 0;
    }
    .location_fields{
        display: flex;
        flex-direction: column;
        justify-content: space-evenly;
    }
    #overlay{	
	position: fixed;
	top: 0;
	z-index: 100;
	width: 100%;
	height:100%;
	display: none;
	background: rgba(0,0,0,0.6);
}
.cv-spinner {
	height: 100%;
	display: flex;
	justify-content: center;
	align-items: center;  
}
.spinner {
	width: 40px;
	height: 40px;
	border: 4px #ddd solid;
	border-top: 4px #2e93e6 solid;
	border-radius: 50%;
	animation: sp-anime 0.8s infinite linear;
}
@keyframes sp-anime {
	0% { 
		transform: rotate(0deg); 
	}
	100% { 
		transform: rotate(359deg); 
	}
}
.is-hide{
	display:none;
}

</style>

<!-- side bar style start-->
<style>
    .bg-white{
        background: #fff;
        color: #000;
    }
</style>
<!-- side bar style end -->

<body>

        <div>
            You might have registered with us earlier with the same email id with which you created your google or github or linkedin account. Please try to sign in without git, google or linked in.
            We will redirect you to the home page
        </div>
    <!-- <script src="/profiles/js/jquery-3.3.1.min.js"></script> -->
    <!-- <script src="/profiles/js/jquery-ui.min.js"></script> -->
    <!-- <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script> -->
    <script src="/static/profiles/js/jquery-3.3.1.min.js"></script>
    <script src="/static/profiles/js/jquery-ui.min.js"></script>

    <script src="/static/profiles/js/popper.min.js"></script>
    <!-- <script src="/profiles/js/jquery-3.2.1.slim.min.js"></script> -->
    <script src="/static/profiles/js/bootstrap.min.js"></script>
    <!-- <script src="/profiles/js/jquery.validate.min.js"></script> -->
    <!-- <script src="/profiles/js/parsley.min.js"></script> -->
    <script src="/static/profiles/js/custom.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/js/select2.min.js"></script> 
    <script src="/static/profiles/js/notification.js"></script>
    <!-- <script src="js/jquery-3.2.1.slim.min.js"></script>
    <script src="/js/popper.min.js"></script>
    <script src="/js/bootstrap.min.js"></script>
    <script src="/js/custom.js"></script> -->
    <script src="/static/seller1/js/owl.carousel.min.js"></script>

<script>
    $(document).ready(function(){
        setTimeout(function(){
            window.location.href='https://www.bverge.com';
        },1500)
    })
</script>

</body>

</html>

profiles/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Database{% endblock %}</title>
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

profiles/templates/home.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>

<body>
    <h1>This is the home page</h1>
	<p>Welcome, {{ user.get_username }}. Thanks for logging in.</p>
	<a href="{% url 'profiles:logout' %}">logout</a>
</body>

</html>

profiles/templates/login.html
{% extends 'base.html' %} {% block content %}
<h2>Log In</h2>
<form method="post">
	{% csrf_token %} {% for field in form %}
	<p>
		{{ field.label_tag }}
		<br> {{ field }} {% if field.help_text %}
		<small style="color: grey">{{ field.help_text }}</small>
		{% endif %} {% for error in field.errors %}
		<p style="color: red">{{ error }}</p>
		{% endfor %}
	</p>
	{% endfor %}
	{% for error in form.non_field_errors %}
		<p style="color: red">{{ error }}</p>
		{% endfor %}
	<button type="submit">Log In</button>
</form>
<p>Not registered ?</p>
<a href="{% url 'profiles:signup' %}">signup</a>

{% endblock %}

profiles/templates/payment_cancelled.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Payment Cancelled</title>
</head>
<body>
    <p>Payment Cancelled</p>
</body>
</html>

profiles/templates/payment_done.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Payment Done</title>
</head>
<body>
    <p>Payment Done</p>
</body>
</html>

profiles/templates/process_subscription.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h4>Subscribe using PayPal</h4>
    {{ form.render }}
</body>
</html>

profiles/templates/signup.html
{% extends 'base.html' %} {% block content %}
<h2>Sign Up</h2>
<form method="post" enctype="multipart/form-data">
	{% csrf_token %} {% for field in form %}
	<p>
		{{ field.label_tag }}
		<br> {{ field }} {% if field.help_text %}
		<small style="color: grey">{{ field.help_text }}</small>
		{% endif %} {% for error in field.errors %}
		<p style="color: red">{{ error }}</p>
		{% endfor %}


	</p>
	{% endfor %}
	{% for error in form.non_field_errors %}
		<p style="color: red">{{ error }}</p>
		{% endfor %}

	{% for field in profile_form %}
	<p>
		{{ field.label_tag }}
		<br> {{ field }} {% if field.help_text %}
		<small style="color: grey">{{ field.help_text }}</small>
		{% endif %} {% for error in field.errors %}
		<p style="color: red">{{ error }}</p>
		{% endfor %}


	</p>
	{% endfor %}
	{% for error in profile_form.non_field_errors %}
		<p style="color: red">{{ error }}</p>
		{% endfor %}

	<button type="submit">Sign Up</button>
</form>
<p>Already have an account ?</p>
<a href="{% url 'profiles:login' %}">login</a>

{% endblock %}

profiles/templates/subscription_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form action="" method="post">
        {% csrf_token %}
        <select name="plans" >
            {% if user.profile.trial %}
            <option value="trial" >Free Trial period for 1 Month</option>
            {% endif %}
            <option value="1-month" >1-Month subscription ($10 USD/Mon)</option>
            <option value="6-month" >6-Month subscription Save $10 ($50 USD/Mon)</option>
            <option value="1-year" >1-Year subscription Save $30 ($90 USD/Mon)</option>
        </select>
        <input type="submit" value="Subscribe">
    </form>
</body>
</html>