album/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url('add/',views.Albumcreate, name='album-create'),
    url('basic-upload/', views.post, name='basic_upload'),
    url('remove/', views.removeFile, name='remove'),
]

chat/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

urlpatterns = [
    # path('api/', views.ChatListView.as_view()),
    path('upload_files', views.upload_file, name='upload-file'),
    path('close', views.chat_close, name='chat-close'),
    path('pdf_view/<file_name>', views.pdf_view, name='pdf-view'),
    path('make-invest', views.make_chat_invest, name='chat-invest'),
    path('make-advise', views.make_chat_advisor, name='chat-advise'),
    path('make-sell', views.make_chat_seller, name='chat-sell'),
    path('fetch-sell/<business_id>', views.fetch_sell_id, name='fetch-sell-id'),
    path('api/<username>', views.get_all_chats),
    path('create/', views.ChatCreateView.as_view()),
    path('<pk>', views.ChatDetailView.as_view()),
    path('<pk>/update/', views.ChatUpdateView.as_view()),
    path('<pk>/delete/', views.ChatDeleteView.as_view()),
    url(r'^$', views.index, name='index'),
    path('<room_name>/', views.room, name='room'),
    path('check_chat', views.staff_check_connection, name='check_chat'),
    path('close_service', views.staff_close_connection, name='close_service'),
    path('send_whatsapp_message', views.send_whatsapp_message, name='send_whatsapp_message'),
    path('handle_incoming_messages', views.handle_incoming_messages, name='handle_incoming_messages'),


]

projectx/urls.py
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url


urlpatterns = [
    re_path(r'^', include(('profiles.urls', 'profiles'), namespace='profiles')),
    re_path(r'^seller/', include(('seller1.urls', 'seller1'), namespace='seller1')),
    re_path(r'^metadata/', include(('metadata.urls', 'metadata'), namespace='metadata')),
    re_path(r'^album/', include(('album.urls', 'album'), namespace='album')),
    re_path(r'^chat/', include(('chat.urls', 'chat'), namespace='chat')),
    re_path(r'^investor/', include(('investor.urls', 'investor'), namespace='investor')),
    re_path(r'^advisor/', include(('advisor.urls', 'advisor'), namespace='advisor')),
    re_path(r'^staff/authorize/login/', include(('staff.urls', 'staff'), namespace='staff   ')),
    re_path(r'^oauth/', include('social_django.urls', namespace='social')),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

album/models.py
from django.db import models
from django.db.models.signals import post_delete
from django.dispatch import receiver
from seller1.models import SellBusiness



class File(models.Model):
    file_id = models.AutoField(primary_key=True, auto_created=True)
    file = models.FileField(upload_to='files/')
    name = models.CharField(max_length=200, blank=True, default=True)
    # seller = models.ManyToManyField(SellBusiness, blank=True, null=True)

    def __str__(self):
        return self.file.name

    def save(self, *args, **kwargs):
        self.name = self.file.name
        super(File, self).save(*args, **kwargs)


class KAlbumForFile(models.Model):
    album_id = models.AutoField(primary_key=True)
    files = models.ManyToManyField(File, blank=True, null=True)
    seller = models.ManyToManyField(SellBusiness, blank=True, null=True)

@receiver(post_delete, sender=File)
def submission_delete(sender, instance, **kwargs):
    instance.file.delete(False) 

album/forms.py
from .models import File
from django import forms

class FileForm(forms.ModelForm):
    class Meta:
        model = File
        fields = '__all__'
        widgets = {

            'file': forms.ClearableFileInput(attrs={'multiple': True})
        }

album/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.views import View

from .forms import FileForm
from .models import File, KAlbumForFile
from django.views.decorators.csrf import csrf_exempt, ensure_csrf_cookie



@csrf_exempt
def post2(request):
    a=True
    if a:
        if request.method == 'POST':
            page_1 = PhotoForm(request.POST, request.FILES)
            files = request.FILES.getlist('file')
            print(request.FILES['file'].name)
            if page_1.is_valid():
                page_1.title=request.FILES['file'].name
                photo = page_1.save()
            else:
                print(page_1.errors)

        return render(request, 'album/upload.html')

    else:
        return redirect('album/upload.html')

@csrf_exempt
def post(request):

    if request.method=='POST':
        files = request.FILES.getlist('file')
        print(files)
        print(files[0].name)
        ac_name=files[0].name
        form = FileForm(request.POST, request.FILES)
        file = form.save()
        file.name=ac_name
        file.save()

        file_id = file.file_id
        print(file.name)
        data_send = {}
        data_send['file_id'] = file_id
        data_send['name']=file.name
        return JsonResponse(data_send, safe=False)
    return render(request, 'album/upload.html')


@csrf_exempt
def removeFile(request):
    if request.method == 'POST':
        print(request.POST['reque'])
        file_id="files/"+request.POST['name']
        print(file_id)
        filer = File.objects.get(name=file_id)

        filer.delete()
        data_send = {}
        return JsonResponse(data_send, safe=False)


@csrf_exempt
def removeFile2(request):
    if request.method == 'POST':
        album_id = request.POST['album_id']
        file_id = request.POST['file_id']
        album = Album.objects.get(album_id=album_id)
        filer = File.objects.get(file_id=file_id)
        for document in filer:
             document.delete()
        data_send = {}
        data_send['error'] = False
        data_send['message'] = 'fine'
        data_send['album_id'] = album_id
        return JsonResponse(data_send, safe=False)

@csrf_exempt
def Albumcreate(request):
    if request.method == 'POST':
        name = "files/" + request.POST['name']
        print(name)
        filer = File.objects.get(name=name)
        initialize = request.POST['initialize']
        print(initialize)
        if initialize=='true':
            print('true')
            album = KAlbumForFile()
            album.save()
            album.files.add(filer)
            album.save()
            data_send = {}
            data_send['error'] = False
            data_send['message'] = 'fine'
            data_send['album_id'] = album.album_id
        else :
            print('false')
            album_id = request.POST['album_id']
            album = KAlbumForFile.objects.get(album_id=album_id)
            album.files.add(filer)
            album.save()
            data_send = {}
            data_send['error'] = False
            data_send['message'] = 'fine'
            data_send['album_id'] = album.album_id
        return JsonResponse(data_send, safe=False)

album/templates/album/upload.html
{% load staticfiles %}


<!DOCTYPE html>
<html lang="en">

<head>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static "album/css/dropzone.css" %}">
    <script src="{% static "album/js/dropzone.js" %}"></script>

</head>
<style>
.container{
 margin: 0 auto;
 width: 50%;
}

.content{
 padding: 5px;
 margin: 0 auto;
}
.content span{
 width: 250px;
}

.dz-message{
 text-align: center;
 font-size: 28px;
}
</style>

 <body >
  <div class="container" >
   <div class='content'>
    <form action="{% url "album:basic_upload"%}" class="dropzone" id="dropzonewidget">
 
    </form> 
   </div> 
  </div>
 </body>

<script>

Dropzone.autoDiscover = false;



$(".dropzone").dropzone({
   dictDefaultMessage: "Add Your Image here",
      init: function() {   
     this.on("addedfile", function(file) {
       if (this.files.length) {
         var _i, _len, _ref = this.files.slice();
         for (_i = 0, _len = this.files.length; _i < _len - 1; _i++) {
                            if (_ref[_i].name === file.name && _ref[_i].size === file.size) {
                                var r = confirm("Overrite existing file");
                                if (r == true) {
                                    this.removeFile(_ref[_i]);
                                }
                                
                            }
                        }
                    }
                });
    }, 
 addRemoveLinks: true,
    removedfile: function (file) {
       $.ajax({
     type: 'POST',
     url: '{% url "album:remove"%}',
     data: {name: file.name,reque:2},
     sucess: function(data){
        //console.log('success: ' + data);
     }
   }); 
			var _ref;
			return(_ref = file.previewElement) != null
				? _ref.parentNode.removeChild(file.previewElement)
				: void 0;   
    },

});
</script>



</html>