chat/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

urlpatterns = [
    # path('api/', views.ChatListView.as_view()),
    path('upload_files', views.upload_file, name='upload-file'),
    path('close', views.chat_close, name='chat-close'),
    path('pdf_view/<file_name>', views.pdf_view, name='pdf-view'),
    path('make-invest', views.make_chat_invest, name='chat-invest'),
    path('make-advise', views.make_chat_advisor, name='chat-advise'),
    path('make-sell', views.make_chat_seller, name='chat-sell'),
    path('fetch-sell/<business_id>', views.fetch_sell_id, name='fetch-sell-id'),
    path('api/<username>', views.get_all_chats),
    path('create/', views.ChatCreateView.as_view()),
    path('<pk>', views.ChatDetailView.as_view()),
    path('<pk>/update/', views.ChatUpdateView.as_view()),
    path('<pk>/delete/', views.ChatDeleteView.as_view()),
    url(r'^$', views.index, name='index'),
    path('<room_name>/', views.room, name='room'),
    path('check_chat', views.staff_check_connection, name='check_chat'),
    path('close_service', views.staff_close_connection, name='close_service'),
    path('send_whatsapp_message', views.send_whatsapp_message, name='send_whatsapp_message'),
    path('handle_incoming_messages', views.handle_incoming_messages, name='handle_incoming_messages'),


]

projectx/urls.py
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url


urlpatterns = [
    re_path(r'^', include(('profiles.urls', 'profiles'), namespace='profiles')),
    re_path(r'^seller/', include(('seller1.urls', 'seller1'), namespace='seller1')),
    re_path(r'^metadata/', include(('metadata.urls', 'metadata'), namespace='metadata')),
    re_path(r'^album/', include(('album.urls', 'album'), namespace='album')),
    re_path(r'^chat/', include(('chat.urls', 'chat'), namespace='chat')),
    re_path(r'^investor/', include(('investor.urls', 'investor'), namespace='investor')),
    re_path(r'^advisor/', include(('advisor.urls', 'advisor'), namespace='advisor')),
    re_path(r'^staff/authorize/login/', include(('staff.urls', 'staff'), namespace='staff   ')),
    re_path(r'^oauth/', include('social_django.urls', namespace='social')),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

seller1/urls.py
from django.urls import path, re_path
from . import views
from django.conf.urls import url
from django.urls import path
from seller1.sms import otp_message, email_message, email_forgot, forgot_password, email_consent, mobile_request

urlpatterns = [
    url('ajax/otp/', otp_message, name='otp-message'),
    url('ajax/email/', email_message, name='email-message'),
    url('ajax/email_consent/', email_consent, name='email-message-consent'),
    url('add_viewer/', views.add_viewer, name='add-viewer'),
    url('check-email/', email_forgot, name='check-email'),
    url('save_view/', views.save_view, name='save-view'),
    url('mobile_check/', mobile_request, name='mobile-check'),
    url('forgot-password/', forgot_password, name='forgot-password'),
    path('bcard/<business_id>', views.seller_render_to_pdf, name='seller-image'),
    url('ajax/update/files/', views.UpdateFiles, name='business-update-files'),
    url('ajax/validate/rev/', views.validate_rev, name='business-validate-rev'),
    url('ajax/validate/bsn/', views.validate_bsn, name='business-validate-bsn'),
    url('ajax/validate/asset/', views.validate_asset, name='business-validate-asset'),
    url('ajax/validate/equity/', views.validate_equity, name='business-validate-equity'),
    url('ajax/validate/loan/', views.validate_loan, name='business-validate-loan'),
    url('ajax/validate/startup/', views.validate_startup, name='business-validate-startup'),
    url('ajax/validate/app/', views.validate_app, name='business-validate-app'),
    url('ajax/validate/ipcode/', views.validate_ipcode, name='business-validate-ipcode'),
    url('ajax/validate/franchise/', views.validate_franchise, name='business-validate-franchise'),
    url('ajax/validate/supplier/', views.validate_supplier, name='business-validate-supplier'),
    path('delete/<business_id>', views.SellBusinessDelete, name='business-delete'),
    path('asset/delete/<business_id>', views.SellAssetDelete, name='asset-delete'),
    path('app/delete/<business_id>', views.SellAppDelete, name='app-delete'),
    path('loan/delete/<business_id>', views.RaiseLoanDelete, name='loan-delete'),
    path('equity/delete/<business_id>', views.SellEquityDelete, name='equity-delete'),
    path('ipcode/delete/<business_id>', views.SellIpcodeDelete, name='ipcode-delete'),
    path('franchise/delete/<business_id>', views.SellFranchiseDelete, name='franchise-delete'),
    path('startup/delete/<business_id>', views.SellStartupDelete, name='startup-delete'),
    path('supplier/delete/<business_id>', views.SellSupplierDelete, name='supplier-delete'),
    url('ajax/validate/$', views.validate, name='business-validate'),
    re_path(r'^$', views.seller, name='seller'),
    path('asset', views.seller_asset, name='asset'),
    path('equity', views.seller_equity, name='equity'),
    path('loan', views.seller_loan, name='loan'),
    path('startup', views.seller_startup, name='startup'),
    path('app', views.seller_app, name='app'),
    path('ipcode', views.seller_ipcode, name='ipcode'),
    path('franchise', views.seller_franchise, name='franchise'),
    path('supplier', views.seller_supplier, name='supplier'),
    path('seller_update/<business_id>', views.SellerUpdate, name='business-update'),
    path('asset_update/<business_id>', views.AssetUpdate, name='asset-update'),
    path('equity_update/<business_id>', views.EquityUpdate, name='equity-update'),
    path('loan_update/<business_id>', views.LoanUpdate, name='loan-update'),
    path('startup_update/<business_id>', views.StartupUpdate, name='startup-update'),
    path('app_update/<business_id>', views.AppUpdate, name='app-update'),
    path('ipcode_update/<business_id>', views.IpcodeUpdate, name='ipcode-update'),
    path('franchise_update/<business_id>', views.FranchiseUpdate, name='franchise-update'),
    path('supplier_update/<business_id>', views.SupplierUpdate, name='supplier-update'),
    path('seller_detail/<business_id>', views.BusinessDetail, name='business-detail'),
    path('user_detail/<business_id>', views.detail_sell_type, name='seller-user-detail'),
    path('all_detail/<business_id>', views.just_sell_type, name='seller-all-detail'),
    path('display/business', views.display_busi, name='seller-display-busi'),
    path('display/web', views.display_web, name='seller-display-web'),
    path('display/startup', views.display_startup, name='seller-display-startup'),
    path('display/franchise', views.display_franchise, name='seller-display-franchise'),
    path('display/supplier', views.display_supplier, name='seller-display-supplier'),
    path('display/advisors', views.display_advise, name='seller-display-advisors'),
    path('display/advisors_startup', views.display_advise_startup, name='seller-display-advisors_startup'),
    path('display/investors', views.display_invest, name='seller-display-investors'),
    path('get_sellers/business', views.show_sellers, name='get_sellers'),
    path('get_advisors/business', views.show_advisors, name='get_advisors'),
    path('get_advisors_startup/business', views.show_advisors_startup, name='get_advisors_startup'),
    path('get_investors/business', views.show_investors, name='get_investors'),
    path('just_add', views.just_add_cart, name='just_add'),
    path('just_remove', views.just_remove_cart, name='just_remove'),
    path('add_seller_cart', views.add_sell_cart, name='add_sell_cart'),
    path('remove_seller_cart', views.remove_sell_cart, name='remove_sell_cart'),
    path('add_investor_cart', views.add_invest_cart, name='add_invest_cart'),
    path('remove_investor_cart', views.remove_invest_cart, name='remove_invest_cart'),
    path('add_advisor_cart', views.add_advise_cart, name='add_advise_cart'),
    path('remove_advisor_cart', views.remove_advise_cart, name='remove_advise_cart'),
    path('fetch-detail/<business_id>', views.fetch_detail_id, name='fetch-sell-id'),
    path('fetch-sell/<business_id>', views.fetch_sell_id, name='fetch-sell-id'),
    path('fetch-advise/<business_id>', views.fetch_advise_id, name='fetch-sell-id'),
    path('fetch-invest/<business_id>', views.fetch_invest_id, name='fetch-sell-id'),

    url('get_model_fields/', views.getModelfields, name='business-model_fields'),
]

staff/urls.py
from django.urls import path,  include
from staff import views, listings
from chat.views import staff_whatsapp

urlpatterns = [
    path('newtask', views.create_Task, name='staff-home'),
    path('whatsapp', staff_whatsapp, name='staff-whatsapp'),
    path('generate_otps', views.createRegTask, name='generate-otps'),
    path('regtask', views.createRegUser, name='client-reg'),
    path('business_task/<task_hash>', listings.Business_task, name='business_task'),
    path('asset_task/<task_hash>', listings.Asset_task, name='asset_task'),
    path('loan_task/<task_hash>', listings.Loan_task, name='loan_task'),
    path('equity_task/<task_hash>', listings.Equity_task, name='equity_task'),
    path('startup_task/<task_hash>', listings.Startup_task, name='startup_task'),
    path('ipcode_task/<task_hash>', listings.Ipcode_task, name='ipcode_task'),
    path('application_task/<task_hash>', listings.App_task, name='app_task'),
    path('franchise_task/<task_hash>', listings.Franchise_task, name='franchise_task'),
    path('supplier_task/<task_hash>', listings.Supplier_task, name='supplier_task'),


]

staff/models.py
from django.db import models
from django.contrib.auth.models import User
from user_seller.models import Sell, Advise, Invest
from django.utils import timezone
import uuid
from datetime import datetime, timedelta
# Create your models here.

class Task(models.Model):
    task_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, related_name='staff_task')
    client = models.ForeignKey(User, blank=True, null=True, related_name='client_task', on_delete=models.CASCADE)
    client_email = models.EmailField(blank=True, null=True)
    listing_type = models.CharField(max_length=255, blank=True, null=True)
    lead_type = models.CharField(max_length=255, blank=True, null=True)
    sell = models.OneToOneField(Sell, blank=True, null=True, on_delete=models.CASCADE)
    advise = models.OneToOneField(Advise, blank=True, null=True, on_delete=models.CASCADE)
    invest = models.OneToOneField(Invest, blank=True, null=True, on_delete=models.CASCADE)
    task_hash = models.CharField(blank=False, max_length=255, unique=True)
    task_enc = models.CharField(blank=False, max_length=255, unique=True)
    expires = models.DateTimeField(blank=True, null=True)
    created_at = models.DateTimeField(default=timezone.now, editable=False)
    completed = models.BooleanField(default=False)

    def __str__(self):
        return self.client.profile.first_name

    def save(self, *args, **kwargs):

        super(Task, self).save(*args, **kwargs)

class RegTask(models.Model):
    reg_task_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True, related_name='staff_reg_task')
    client_email = models.EmailField(blank=True, null=True)
    client_phone = models.CharField(max_length=255, blank=True, null=True)
    country_code_primary = models.CharField(max_length=255, default="+91")
    otp_email = models.CharField(max_length=255, blank=True, null=True)
    otp_phone = models.CharField(max_length=255, blank=True, null=True)
    client = models.ForeignKey(User, blank=True, null=True, related_name='client_reg_task', on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now, editable=False)

class EmailModel(models.Model):
    model_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    email = models.EmailField(blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, related_name='user_emails')
    created_at = models.DateTimeField(default=timezone.now, editable=False)

class PhoneModel(models.Model):
    model_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    phone_number = models.CharField(max_length=255, blank=True, null=True)
    country_code_primary = models.CharField(max_length=255, default="+91")
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, related_name='user_phones')
    created_at = models.DateTimeField(default=timezone.now, editable=False)

staff/forms.py
from django import forms
from .models import Task, RegTask

SELL = 'Sell'
ADVISE = 'Advise'
INVEST = 'Invest'
Listing_CHOICES = (
	(SELL, 'Sell'),
	# (ADVISE, 'Advise'),
	# (INVEST, 'Invest')
)

BUSINESS = 'Business'
BUSINESS_ADVISE = 'Business_Advisor'
ASSET = 'Asset'
EQUITY = 'Equity'
LOAN = 'Loan'
SUPPLIER = 'Supplier'
FRANCHISE = 'Franchise'
STARTUP = 'Startup'
STARTUP_ADVISE = 'Startup_Advisor'
IP_CODES = 'IP_Codes'
APP = 'Application'
INDIVIDUAL_INVEST = 'Individual'
COMPANY_INVEST = 'Company'
Lead_CHOICES = (
	(BUSINESS, 'Business'),
	(ASSET, 'Asset'),
	(EQUITY, 'Equity'),
    (LOAN, 'Loan'),
    (SUPPLIER, 'Supplier'),
    (FRANCHISE, 'Franchise'),
    (STARTUP, 'Startup'),
    (IP_CODES, 'IP_Codes'),
    (APP, 'Application'),
    # (BUSINESS_ADVISE, 'Business_Advisor'),
    # (STARTUP_ADVISE, 'Startup_Advisor'),
    # (INDIVIDUAL_INVEST, 'Individual_Investor'),
    # (COMPANY_INVEST, 'Company_Investor'),
)

class TaskForm(forms.ModelForm):

    listing_type = forms.ChoiceField(choices=Listing_CHOICES, widget=forms.RadioSelect, initial=Listing_CHOICES[0],
                                     required=True)
    lead_type = forms.ChoiceField(choices=Lead_CHOICES, widget=forms.RadioSelect, initial=Lead_CHOICES[0],
                                     required=True)
    client_email = forms.EmailField(required=True)
    # phone_number = forms.IntegerField()
    name = forms.CharField(required=True, max_length=255)
    class Meta:
        model = Task
        exclude = ['created_at', 'completed', 'task_enc',
                   'task_hash', 'sell', 'advise', 'invest', 'task_id', 'user', 'client', 'expires']

class RegTaskForm(forms.ModelForm):

    reg_task_id = forms.CharField(max_length=255, required=False)
    first_name = forms.CharField(max_length=255, required=False)
    last_name = forms.CharField(max_length=255, required=False)

    class Meta:
        model = RegTask
        exclude = ['created_at', 'user', 'client']

staff/templates/staff/client_reg.html
<!-- templates/base.html -->
<!DOCTYPE html>
<html>
<head>
  
  {% load staticfiles %}
        {% load widget_tweaks %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Bverge || Sell Franchise</title>
    <link rel="stylesheet" href="/static/seller1/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/seller1/css/w3.css">
    <link rel="stylesheet" href="/static/seller1/css/jquery-ui.min.css">
    <link rel="stylesheet" href="/static/seller1/css/style.css">
    <link rel="stylesheet" href="/static/seller1/css/parsley.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="icon" href="/static/profiles/images/icon1.png">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/css/select2.min.css" rel="stylesheet" />
        <link rel="stylesheet" href="/static/seller1/css/dropzone.css">
    <script src="/static/seller1/js/dropzone.js"></script>
  <title>Bverge Staff</title>
</head>
<style>
    #feeback_modal .close{
    position: absolute;
    right: 16px;
    top: 18px;
    padding: 8px;
    }
    #modal_edit_profile .close{
    position: absolute;
    right: 16px;
    top: 18px;
    padding: 8px;
    }
    #modal_change_password .close{
    position: absolute;
    right: 16px;
    top: 18px;
    padding: 8px;
    }
    #signup .profile_section{
    display: flex;
    flex-direction: column;
    justify-content: space-between;
    }
    .f-40{
    font-size: 40px;
    }
    .modal-content{
    box-shadow:2px 3px 10px 0px rgba(0,0,0,1);
    }

    .pac-container {
        z-index:20000;
    }
    .lodal {
        display:    none;
        position:   fixed;
        z-index:    1000000000000000;
        top:        0;
        left:       0;
        height:     100%;
        width:      100%;
        background: rgba( 255, 255, 255, .8 )
                    url('https://i.stack.imgur.com/FhHRx.gif')
                    50% 50%
                    no-repeat;
    }
    #mlodal {

        position:   fixed;
        z-index:    10000000000000000;
        top:        0;
        left:       0;
        height:     100%;
        width:      100%;
        background: rgba( 255, 255, 255, .8 )
                    url('https://i.stack.imgur.com/FhHRx.gif')
                    50% 50%
                    no-repeat;
    }
    #nlodal_s {

position:   fixed;
z-index:    10000000000000000;
top:        0;
left:       0;
height:     100%;
width:      100%;
background: rgba( 255, 255, 255, .8 )
            url('https://i.stack.imgur.com/FhHRx.gif')
            50% 50%
            no-repeat;
}
#nlodal_b {

position:   fixed;
z-index:    10000000000000000;
top:        0;
left:       0;
height:     100%;
width:      100%;
background: rgba( 255, 255, 255, .8 )
            url('https://i.stack.imgur.com/FhHRx.gif')
            50% 50%
            no-repeat;
}

    /* When the body has the loading class, we turn
    the scrollbar off with overflow:hidden */
    body.loading .lodal {
        overflow: hidden;
    }

    /* Anytime the body has the loading class, our
    modal element will be visible */
    body.loading .lodal {
        display: block;
    }
    div#notif_loader_s.loading .lodal {
        overflow: hidden;
    }
    div#notif_loader_s.loading .lodal {
        display: block;
    }
    .h-51{
    height: 51px !important;
    }
    .border-r-0{
    border-top-right-radius: 0;
    border-bottom-right-radius: 0;
    }
    .border-r-all{
    border-radius: 0;
    }
    .location_fields{
        display: flex;
        flex-direction: column;
        justify-content: space-evenly;
    }
    #overlay{	
	position: fixed;
	top: 0;
	z-index: 100;
	width: 100%;
	height:100%;
	display: none;
	background: rgba(0,0,0,0.6);
}
.cv-spinner {
	height: 100%;
	display: flex;
	justify-content: center;
	align-items: center;  
}
.spinner {
	width: 40px;
	height: 40px;
	border: 4px #ddd solid;
	border-top: 4px #2e93e6 solid;
	border-radius: 50%;
	animation: sp-anime 0.8s infinite linear;
}
@keyframes sp-anime {
	0% { 
		transform: rotate(0deg); 
	}
	100% { 
		transform: rotate(359deg); 
	}
}
.is-hide{
	display:none;
}

/* .fa-google {
  background: conic-gradient(from -45deg, #ea4335 110deg, #4285f4 90deg 180deg, #34a853 180deg 270deg, #fbbc05 270deg) 73% 55%/150% 150% no-repeat;
  -webkit-background-clip: text;
  background-clip: text;
  color: transparent;
  -webkit-text-fill-color: transparent;
} */

</style>
<body>

	<div id="overlay">
		<div class="cv-spinner">
			<span class="spinner"></span>
		</div>
	</div>
  
<h2>Register a Client</h2>
<form id="task_form" method="post">
    {% csrf_token %}
    
    <p>
		{{ task_form.first_name.label_tag }}
		<br> {{ task_form.first_name }} {% if task_form.first_name.help_text %}
		<small style="color: grey">{{ task_form.first_name.help_text }}</small>
		{% endif %} {% for error in task_form.first_name.errors %}
		<p style="color: red">{{ error }}</p>
		{% endfor %}
    </p>
    
    <p>
		{{ task_form.last_name.label_tag }}
		<br> {{ task_form.last_name }} {% if task_form.last_name.help_text %}
		<small style="color: grey">{{ task_form.last_name.help_text }}</small>
		{% endif %} {% for error in task_form.last_name.errors %}
		<p style="color: red">{{ error }}</p>
		{% endfor %}
	</p>

	

    <p>
		{{ task_form.client_email.label_tag }}
		<br> {{ task_form.client_email }} {% if task_form.client_email.help_text %}
		<small style="color: grey">{{ task_form.client_email.help_text }}</small>
		{% endif %} {% for error in task_form.client_email.errors %}
		<p style="color: red">{{ error }}</p>
		{% endfor %}
    </p>

    <div class="container-fluid zero-padding">
        <div class="row">
           <div class="col-sm-6">
               <!-- <input type="text" name="pass" id="pass" class="form-control col-sm-12" maxlength="4" placeholder="Country Code"> -->
               <label for="" class="f-16 pl-1 pt-10">Country Code</label>
               <select class="form-control" name= "country_code_primary" id="country_code_primary">
                        {% for x in code_data %}
                        <option data-iso="{{x.iso}}" value="+{{x.dialing}}">{{x.code}}</option>

                        {% endfor %}
              </select>
           </div>
           <div class="col-sm-6">

<label for="{{ task_form.client_phone.id_for_label }}" class="f-16 pl-1 pt-15">Phone number</label>
            {{ task_form.client_phone|add_class:"form-control col-sm-12 ginput begin_empty" |append_attr:"placeholder:Phone Number"}}
            <div class="errors" id="email_err" style="color: red">
                {{ task_form.client_phone.errors }}
            </div>

           </div>
        </div>
    </div>

    <p id="otp_email_para" style="display: none;" >
		{{ task_form.otp_email.label_tag }}
		<br> {{ task_form.otp_email }} {% if task_form.otp_email.help_text %}
		<small style="color: grey">{{ task_form.otp_email.help_text }}</small>
		{% endif %} {% for error in task_form.otp_email.errors %}
		<p style="color: red">{{ error }}</p>
		{% endfor %}
    </p>

    <!-- <p id="otp_phone_para" style="display: none;" >
		{{ task_form.otp_phone.label_tag }}
		<br> {{ task_form.otp_phone }} {% if task_form.otp_phone.help_text %}
		<small style="color: grey">{{ task_form.otp_phone.help_text }}</small>
		{% endif %} {% for error in task_form.otp_phone.errors %}
		<p style="color: red">{{ error }}</p>
		{% endfor %}
    </p> -->

    <button type="button" id="generate_otp">Generate OTPs</button>

    

    <p id="reg_task_id_para" style="display: none;" >
		{{ task_form.reg_task_id.label_tag }}
		<br> {{ task_form.reg_task_id }} {% if task_form.reg_task_id.help_text %}
		<small style="color: grey">{{ task_form.reg_task_id.help_text }}</small>
		{% endif %} {% for error in task_form.reg_task_id.errors %}
		<p style="color: red">{{ error }}</p>
		{% endfor %}
    </p>
    
    
	
	<button type="submit" id="task_submit">Register Client</button>
</form>

<div class="modal" id="otp_modal">
	<div class="modal-dialog modal-lg modal-dialog-centered">
		<div class="modal-content">
			<div class="modal-header d-flex align-items-center" style="background: url('static/profiles/images/homepage-banner.png');background-size: cover;background-position: center; height: 150px;">
				<a class="navbar-brand w-100 text-center pl-4 f-40 font-weight-bold c-f ff-pd" href="">Business Verge</a>
				<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
					<!-- <h4 class="modal-title">Modal header</h4> -->
				</div>
	<div class="modal-body text-center">
		<!-- <div id="otp_body" >
			<label for="otp" class="f-16 f-w-500 pt-30">OTP please, for phone number verification</label>
			<input type="text" class="form-control col-sm-4 offset-sm-4 text-center" name="otp" id="otp" />
			<div class="otp-btns">
				<button class="btn btn-success" id="otp_verify">Verify</button>
				<button class="btn btn-primary" id="resend_otp">Resend OTP</button>
			</div>
			<p id="otp_err" style="color: red; display: none;" >Wrong OTP</p>
		</div> -->
		<div id="otp_email_body" >
				<label for="otp_email" class="f-16 f-w-500 pt-30">OTP please, for email address verification</label>
				<input type="text" class="form-control col-sm-4 offset-sm-4 text-center" name="otp_email" id="otp_email" />
				<div class="otp-btns">
					<button type="button" class="btn btn-success" id="otp_email_verify">Verify</button>
					<!-- <button class="btn btn-primary" id="resend_otp_email">Resend OTP</button> -->
				</div>
				<p id="otp_email_err" style="color: red; display: none;" >Wrong OTP</p>
			</div>
	</div>
  </div>
</div>
</div>

<div class="lodal" ><!-- Place at bottom of page --></div>
<div id="mlodal" style="display:none" ><!-- Place at bottom of page --></div>


  
  <script src="{% static 'seller1/js/jquery-3.3.1.min.js' %}"></script>
  <script src="{% static 'seller1/js/jquery-ui.min.js' %}"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/js/select2.min.js"></script>
  <script src="{% static 'seller1/js/popper.min.js' %}"></script>
  <script src="{% static 'seller1/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'seller1/js/jquery.validate.min.js' %}"></script>
  <script src="{% static 'seller1/js/currencytagger.js' %}"></script>

  <script>
	  $(document).on({
    ajaxStart: function() { $body.addClass("loading");    },
     ajaxStop: function() { $body.removeClass("loading"); }
});



    $('#generate_otp').on('click', function(){
		if($('#id_first_name').val()==''){
			return 0;
        }
        if($('#id_last_name').val()==''){
			return 0;
		}
		if($('#id_client_email').val()==''){
			return 0;
		}
		if($('#id_client_phone').val()==''){
			return 0;
		}
		var client_email = $('#id_client_email').val();
        var first_name = $('#id_first_name').val();
        var code = $('#country_code_primary').val()
        var client_phone = code+$('#id_client_phone').val();
        var form_data = new FormData();
        form_data.append('client_email', client_email);
        form_data.append('first_name', first_name);
        form_data.append('client_phone', client_phone);
        form_data.append('country_code_primary', code)
        form_data.append('csrfmiddlewaretoken', '{{ csrf_token }}');
        console.log(form_data);
		$("#overlay").fadeIn();
      $.ajax({
                    method:'POST',
                    url : '{% url "staff:generate-otps" %}',
                    data: form_data,
                    processData: false,
                    contentType: false,
                    async: false,
                    success: function(data){
						$("#overlay").fadeOut();
						// $('#otp_modal').modal('show');
                        //console.log(data)
                        if(data.status=='valid'){
                            $('#id_reg_task_id').val(data.reg_id);
                            $('#otp_email_para').show();
                            // $('#otp_phone_para').show();
                            //console.log('email sent');
                        }
                    }
                });
    })
    

  </script>

</body>




</html>